version: "3.8"
services:
  app:
    image: job-fit-cv
    build: ./
    container_name: job-fit-cv
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network
    environment:
      - DATABASE_URL=${DATABASE_URL}


networks:
  shared-network:
    external: true

volumes:
  pgdata:
    driver: local
