version: "3.8"
services:
  app:
    image: riccardo006/job-fit-cv:latest
    container_name: job-fit-cv
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - APP_PORT=${APP_PORT}
      - NEXT_PUBLIC_OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}
      - NEXT_PUBLIC_JOB_RECOMMENDER_PATH=${NEXT_PUBLIC_JOB_RECOMMENDER_PATH}
      - SECRET=${SECRET}
      - APP_ENV=${APP_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - NEXT_PUBLIC_OTHER_PATH=${NEXT_PUBLIC_OTHER_PATH}


networks:
  network:
    driver: bridge

volumes:
  pgdata:
    driver: local
