version: "3.8"
services:
  app:
    image: riccardo006/job-fit-cv:latest
    container_name: job-fit-cv
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  network:
    driver: bridge

volumes:
  pgdata:
    driver: local
