version: "3.8"
services:
  app:
    image: riccardo006/job-fit-cv:latest
    container_name: job-fit-cv
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    container_name: job-fit-cv-db
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job-fit-cv
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d job-fit-cv"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
networks:
  network:
    driver: bridge

volumes:
  pgdata:
    driver: local