version: "3.8"
services:
  app:
    image: job-fit-cv
    container_name: job-fit-cv
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "5000:5000"
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    container_name: job-fit-cv-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job-fit-cv
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d job-fit-cv"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  network:
    driver: bridge

volumes:
  pgdata:
