version: "3.8"
services:
  app:
    image: riccardo006/job-fit-cv:latest
    container_name: job-fit-cv
    ports:
      - "1234:1234"
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/job-fit-cv?schema=public


networks:
  shared-network:
    external: true

volumes:
  pgdata:
    driver: local
